Repository temporalio/roadrunner-temporal, pull requests merged in 2021-03, with the labels that each got.

#37 update(constants): move all shared constants to the one place
  .github/workflows/linters.yml
  .github/workflows/linux.yml
  .golangci.yml
  README.md
  activity/activity_pool.go
  activity/plugin.go
  constants.go
  protocol/proto_codec.go
  tests/src/Workflow/CancelledNestedWorkflow.php
  workflow/plugin.go
  workflow/worker.go
Labels: C-enhancement

#39 ⚡ feat(release): 1.0.0 release
  CHANGELOG.md
  client/plugin.go
  go.mod
  go.sum
  tests/docker-compose.yaml
Labels: C-enhancement

#43 🐛 bug(process:close): Run command directly instead of pushing it to the queue
  CHANGELOG.md
  tests/src/Workflow/CancelledMidflightWorkflow.php
  workflow/process.go
Labels: B-regression

#44 🐛 bug(workflow close): Do not send messages to the worker after destroy command
  go.sum
  tests/.rr.yaml
  tests/cancel_test.go
  workflow/process.go
Labels: B-regression

#46 ⚡ feat(release) release v1.0.1
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement

#52 fix(worker grace timeout): Fix bug with the worker which does not follow common grace period
  .golangci.yml
  activity/activity_pool.go
  activity/plugin.go
  activity/rpc.go
  client/plugin.go
  go.mod
  go.sum
  protocol/json_codec.go
  protocol/message.go
  protocol/proto_codec.go
  protocol/worker_info.go
  tests/cancel_test.go
  tests/hp_test.go
  tests/server_test.go
  tests/signal_test.go
  tests/src/Workflow/CancelSignaledChildWorkflow.php
  tests/src/Workflow/CanceledMidflightWorkflow.php
  tests/src/Workflow/CanceledNestedWorkflow.php
  tests/src/Workflow/CanceledScopeWorkflow.php
  tests/src/Workflow/CanceledSingleScopeWorkflow.php
  tests/src/Workflow/CanceledWithCompensationWorkflow.php
  tests/src/Workflow/CanceledWorkflow.php
  tests/src/Workflow/SignalChildViaStubWorkflow.php
  tests/src/Workflow/SimpleSignaledWorkflow.php
  tests/src/Workflow/SimpleSignaledWorkflowWithSleep.php
  tests/src/Workflow/WorkflowWithSignaledSteps.php
  workflow/canceller.go
  workflow/plugin.go
  workflow/process.go
  workflow/worker.go
Labels: A-module, C-enhancement, beta-nominated, stable-nominated

#53 upd(changelog): Update CHANGELOG
  CHANGELOG.md
Labels: A-docs

#54 fix(grace timeout): Provide grace timeout down to the pool
  activity/activity_pool.go
  activity/plugin.go
Labels: A-other
