Repository temporalio/roadrunner-temporal, pull requests merged in 2021-02, with the labels that each got.

#27 Bug(activities): Workers method return type for the informer plugin
  activity/activity_pool.go
  activity/plugin.go
  client/plugin.go
  tests/src/Workflow/CancelSignalledChildWorkflow.php
  tests/src/Workflow/CancelledMidflightWorkflow.php
  tests/src/Workflow/CancelledNestedWorkflow.php
  tests/src/Workflow/CancelledScopeWorkflow.php
  tests/src/Workflow/CancelledSingleScopeWorkflow.php
  tests/src/Workflow/CancelledWithCompensationWorkflow.php
  tests/src/Workflow/ParallelScopesWorkflow.php
  tests/worker.php
  workflow/plugin.go
Labels: A-module, A-tests

#28 bug(workflow_pool): endless worker process reset
  activity/plugin.go
  go.mod
  go.sum
  tests/disaster_test.go
  tests/docker-compose.yaml
  workflow/plugin.go
  workflow/process.go
  workflow/worker.go
  workflow/workflow_pool.go
Labels: B-bug

#29 feat(release): release beta5
  go.mod
Labels: A-other

#30 stabilization(RC): RR worker stabilization before RC1
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  CHANGELOG.md
  activity/activity_pool.go
  activity/plugin.go
  go.mod
  go.sum
  protocol/json_codec.go
  tests/docker-compose.yaml
  tests/hp_test.go
  utils/toString.go
  workflow/id_registry.go
  workflow/plugin.go
  workflow/process.go
  workflow/worker.go
Labels: A-other

#32 release(RC.2): RC.2 Release
  CHANGELOG.md
  go.mod
  go.sum
  tests/docker-compose.yaml
Labels: A-other

#33 feat(protocol): Explicitly pass panic message
  workflow/process.go
Labels: C-enhancement
