Repository temporalio/roadrunner-temporal, pull requests merged in 2024-02, with the labels that each got.

#469 fix: update proto marshaler from gogo to std
  .github/workflows/linux.yml
  go.mod
  go.sum
  go.work
  go.work.sum
  rpc.go
  tests/go.mod
  tests/go.sum
  tests/rpc_test.go
Labels: B-bug, C-enhancement

#471 feature: implement status
  go.work.sum
  status.go
  tests/configs/.rr-status.yaml
  tests/go.mod
  tests/go.sum
  tests/plugin_status_test.go
Labels: A-tests, C-enhancement

#472 fix: use activity pool instead of workflow
  status.go
Labels: A-tests
