Repository temporalio/roadrunner-temporal, pull requests merged in 2025-01, with the labels that each got.

#606 feat: Add debugging logs
  aggregatedpool/handler.go
Labels: A-other

#599 feature: support typed search attributes
  aggregatedpool/handler.go
  go.mod
  go.sum
  go.work.sum
  internal/protocol.go
  tests/go.mod
  tests/go.sum
Labels: C-enhancement

#605 feature: TSA available on the `StartWorkflow` stage
  aggregatedpool/handler.go
  aggregatedpool/workflow.go
  go.mod
  go.sum
  go.work.sum
  internal/protocol.go
  tests/go.mod
  tests/go.sum
Labels: C-feature-request
